name: Build and Test Projects

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-winforms:
    name: Build .NET 8 WinForms Client
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore WinForms project dependencies
        run: dotnet restore ./client/client.csproj

      - name: Build WinForms project
        run: dotnet build ./client/client.csproj --configuration Release

      - name: Create WinForms artifact
        uses: actions/upload-artifact@v3
        with:
          name: WinFormsClient
          path: ./client/bin/Release/

  build-arduino:
    name: Build Arduino Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Install ESP32 platform
        run: arduino-cli core install esp32:esp32

      - name: Build Arduino Project
        run: arduino-cli compile --fqbn esp32:esp32:esp32c3 --build-path ./server/build  ./server/input_modifier.ino

      - name: Create Arduino artifact
        uses: actions/upload-artifact@v3
        with:
          name: ArduinoApp
          path: ./server/build/
          
  run-tests:
    name: Run CMake Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install CMake
        run: sudo apt-get install cmake
  
      - name: Create build directory
        run: mkdir build && cd build
  
      - name: Configure CMake project
        run: |
          cd build
          cmake ../tests
  
      - name: Build tests
        run: |
          cd build
          cmake --build .
  
      - name: Run tests and save output
        run: |
          cd build
          ./tests > test-results.txt  # Capture the output of the tests executable
  
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results.txt

